"""OpenAI timed transcription with bounded, temporary audio preparation."""

import asyncio
import io
import math
import wave
from array import array
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory

import httpx
from openai import APIError, AsyncOpenAI

from app.pipeline.transcription import TranscriptionPiece, TranscriptionProvider

SAMPLE_RATE = 16_000
MAX_DOWNLOAD_BYTES = 256 * 1024 * 1024
MAX_DURATION_SECONDS = 7_200


@dataclass(frozen=True)
class AudioChunk:
    content: bytes
    offset_seconds: float
    duration_seconds: float


def audio_chunks(path: Path, chunk_seconds: int = 600) -> Iterator[AudioChunk]:
    """Split PCM at sample boundaries, preferring a pause near the boundary.

    Ten minutes of mono 16 kHz PCM is 19.2 MB, below the 25 MB API limit.
    Chunks never overlap or skip samples; timestamps use the actual frame offset.
    """
    with wave.open(str(path), "rb") as source:
        if (source.getnchannels(), source.getsampwidth(), source.getframerate()) != (
            1,
            2,
            SAMPLE_RATE,
        ):
            raise ValueError("audio must be normalized to mono 16 kHz PCM")
        total = source.getnframes()
        if not total or total > MAX_DURATION_SECONDS * SAMPLE_RATE:
            raise ValueError("OpenAI audio must contain between 0 and 120 minutes")
        offset = 0
        while offset < total:
            source.setpos(offset)
            frames = source.readframes(chunk_seconds * SAMPLE_RATE)
            count = len(frames) // 2
            if offset + count < total:
                # Find a quiet 200 ms window in the final five seconds. A hard
                # boundary is used only when no pause exists in that window.
                window = SAMPLE_RATE // 5
                samples = array("h", frames)
                for end in range(count, max(window, count - 5 * SAMPLE_RATE), -window):
                    if max(abs(value) for value in samples[end - window : end]) < 500:
                        count = end - window // 2
                        frames = frames[: count * 2]
                        break
            output = io.BytesIO()
            with wave.open(output, "wb") as target:
                target.setnchannels(1)
                target.setsampwidth(2)
                target.setframerate(SAMPLE_RATE)
                target.writeframes(frames)
            yield AudioChunk(
                output.getvalue(), offset / SAMPLE_RATE, count / SAMPLE_RATE
            )
            offset += count


async def download_audio(url: str, path: Path) -> None:
    # URL is generated by our storage adapter, never supplied directly by a user.
    # A separate client prevents the OpenAI Authorization header reaching storage.
    try:
        async with httpx.AsyncClient(timeout=60, follow_redirects=False) as client:
            async with client.stream("GET", url) as response:
                response.raise_for_status()
                size = 0
                with path.open("wb") as target:
                    async for data in response.aiter_bytes():
                        size += len(data)
                        if size > MAX_DOWNLOAD_BYTES:
                            raise ValueError("OpenAI audio download exceeds 256 MiB")
                        target.write(data)
    except httpx.HTTPError:
        raise ValueError("could not download audio for OpenAI transcription") from None


async def normalize_audio(source: Path, target: Path) -> None:
    try:
        process = await asyncio.create_subprocess_exec(
            "ffmpeg",
            "-nostdin",
            "-v",
            "error",
            "-y",
            "-protocol_whitelist",
            "file,pipe",
            "-format_whitelist",
            "mov,mp3,wav,matroska,webm,ogg,flac,aac",
            "-i",
            str(source),
            "-vn",
            "-ac",
            "1",
            "-ar",
            str(SAMPLE_RATE),
            "-t",
            str(MAX_DURATION_SECONDS + 1),
            "-c:a",
            "pcm_s16le",
            str(target),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
    except FileNotFoundError:
        raise ValueError("ffmpeg is required for OpenAI transcription") from None
    try:
        await asyncio.wait_for(process.wait(), timeout=300)
    except (TimeoutError, asyncio.CancelledError):
        process.kill()
        await process.wait()
        raise
    if process.returncode != 0:
        raise ValueError("audio could not be decoded for OpenAI transcription")


class OpenAITranscriptionProvider(TranscriptionProvider):
    def __init__(self, api_key: str, model: str = "gpt-4o-transcribe-diarize") -> None:
        self._api_key = api_key
        self.model = model

    async def transcribe(
        self, audio_url: str, language: str
    ) -> list[TranscriptionPiece]:
        if not self._api_key.strip():
            raise ValueError("OPENAI_API_KEY is required for OpenAI transcription")
        pieces: list[TranscriptionPiece] = []
        next_speaker = 0
        # Raw audio and normalized chunks are private temporary files, deleted on
        # both success and failure. The original S3 evidence stays unchanged.
        with TemporaryDirectory(prefix="homean-audio-") as directory:
            source, normalized = (
                Path(directory) / "source",
                Path(directory) / "audio.wav",
            )
            await download_audio(audio_url, source)
            await normalize_audio(source, normalized)
            async with AsyncOpenAI(
                api_key=self._api_key, max_retries=2, timeout=300
            ) as client:
                for chunk in audio_chunks(normalized):
                    try:
                        result = await client.audio.transcriptions.create(
                            model=self.model,
                            file=("showing.wav", chunk.content, "audio/wav"),
                            language=language,
                            response_format="diarized_json",
                            chunking_strategy="auto",
                        )
                    except APIError:
                        raise ValueError(
                            "OpenAI transcription request failed; "
                            "check provider access and limits"
                        ) from None
                    segments = getattr(result, "segments", None)
                    if segments is None:
                        raise ValueError("OpenAI transcription omitted timed segments")
                    # Speaker labels are local to an API request. Never imply
                    # that speaker A in two different chunks is the same person.
                    speakers: dict[str, int] = {}
                    for segment in segments:
                        text = segment.text.strip()
                        if not text:
                            continue
                        start, end = float(segment.start), float(segment.end)
                        if (
                            not math.isfinite(start)
                            or not math.isfinite(end)
                            or start < 0
                            or end < start
                            or end > chunk.duration_seconds + 0.25
                        ):
                            raise ValueError("OpenAI returned invalid audio timestamps")
                        label = getattr(segment, "speaker", None)
                        speaker = None
                        if isinstance(label, str) and label.strip():
                            if label not in speakers:
                                speakers[label] = next_speaker
                                next_speaker += 1
                            speaker = speakers[label]
                        pieces.append(
                            TranscriptionPiece(
                                text=text,
                                start_ms=(
                                    chunk.offset_seconds
                                    + min(start, chunk.duration_seconds)
                                )
                                * 1000,
                                end_ms=(
                                    chunk.offset_seconds
                                    + min(end, chunk.duration_seconds)
                                )
                                * 1000,
                                speaker=speaker,
                                # Diarized responses do not supply Deepgram-style
                                # confidence. Null means unknown, never a fake score.
                                confidence=None,
                            )
                        )
        return pieces
